config/routes.rb
CordovaRails::Application.routes.draw do
  root 'jobs#new'
  
  get 'register' => 'users#new', :as => :register
  get 'login' => 'users#login', :as => :login
  post 'login' => 'users#create_session', :as => :create_session
  get 'logout' => 'users#logout', :as => :logout

  resources :users
  resources :jobs
  resources :images
end

app/models/image.rb
class Image < ActiveRecord::Base
  belongs_to :job
  mount_uploader :pic, ImageUploader
end

app/models/job.rb
class Job < ActiveRecord::Base
  belongs_to :user
  has_many :images

  accepts_nested_attributes_for :images, allow_destroy: true
end

app/models/user.rb
require 'bcrypt'

class User < ActiveRecord::Base
  has_many :jobs

  validates :email, :presence => true, :uniqueness => true
  validates :password, :presence => true
  validates :name, :presence => true, :length => {:minimum => 4}

  # Helps encrypt new password
  def self.encrypt_password(pass)
    BCrypt::Password.create(pass).to_s
  end

  # Helps compare a supplied password
  def does_password_match?(supplied_password)
    BCrypt::Password.new(self.password) == supplied_password
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  skip_before_filter  :verify_authenticity_token

  helper_method :user_logged_in?, :current_user

  def authenticate_user
    if not user_logged_in?
      redirect_to login_path
    end
  end

  def add_origin_header
    # For testing on your local machine on a normal browser, change this to your machine's IP
    # headers['Access-Control-Allow-Origin'] = 'http://localhost:8888';
    headers['Access-Control-Allow-Origin'] = 'http://198.199.113.143';
    headers['Access-Control-Allow-Credentials'] = 'true';
    headers['Access-Control-Allow-Methods'] = 'GET, POST';
    headers['Access-Control-Allow-Headers'] = 'X-Requested-With';
  end

  protected

  def current_user
    @user ||= User.find(session[:user_id]) if user_logged_in?
  end

  def user_logged_in?
    not session[:user_id].blank?
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  before_filter :authenticate_user
  after_filter  :add_origin_header

  # GET /jobs
  # GET /jobs.json
  def index
    @jobs = current_user.jobs

    respond_to do |format|
      format.html # index.html.erb
      if params[:callback]
        format.js { render :json => {:jobs => @jobs.as_json(include: :images)}, :callback => params[:callback] }
      else
        format.json { render json: @jobs }
      end
      
    end
  end

  # GET /jobs/1
  # GET /jobs/1.json
  def show
    @job = Job.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @job.to_json(include: :images) }
    end
  end

  # GET /jobs/new
  # GET /jobs/new.json
  def new
    @job = Job.new
    @job.images.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @job }
    end
  end

  # GET /jobs/1/edit
  def edit
    @job = Job.find(params[:id])
  end

  # POST /jobs
  # POST /jobs.json
  def create
    @job = Job.new(job_params)
    @job.user = current_user

    respond_to do |format|
      if @job.save
        params[:images]['pic'].each do |p|
          @images = @job.images.create!(:pic => p, :job_id => @job.id)
        end
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render json: @job, status: :created, location: @job }
      else
        format.html { render action: "new" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /jobs/1
  # PUT /jobs/1.json
  def update
    @job = Job.find(params[:id])

    respond_to do |format|
      if @job.update(job_params)
        format.html { redirect_to @job, notice: 'Job was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @job.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /jobs/1
  # DELETE /jobs/1.json
  def destroy
    @job = Job.find(params[:id])
    @job.destroy

    respond_to do |format|
      format.html { redirect_to jobs_url }
      format.json { head :no_content }
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def job_params
      params.require(:job).permit(:number, :customer, :equipment, images_attributes: [:pic])
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_filter :autenticate_user, :only => [:show, :edit, :update]
  after_filter  :add_origin_header

  # GET /users/1
  # GET /users/1.json
  def show
    @user = User.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/new
  # GET /users/new.json
  def new
    @user = User.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @user }
    end
  end

  # GET /users/1/edit
  def edit
    @user = User.find(params[:id])
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)
    @user.password = User.encrypt_password(@user.password)

    respond_to do |format|
      if @user.save
        # Auto login
        session[:user_id] = @user.id
        format.html { redirect_to jobs_path, notice: 'User was successfully created.' }
        format.json { render json: @user, status: :created, location: @user }
      else
        format.html { render action: "new" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /users/1
  # PUT /users/1.json
  def update
    @user = User.find(params[:id])

    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # GET /logout
  def logout
    session.clear
    redirect_to login_path
  end

  # GET /login
  def login
    @user = User.new
  end

  # POST /login
  def create_session
    email = params[:user][:email]
    password = params[:user][:password]
    if email and password and not (email.blank? or password.blank?)
      if user = User.find_by_email(email) and user.does_password_match?(password)
        session[:user_id] = user.id
        respond_to do |format|
          format.html { redirect_to root_path }
          format.json { render :json => {:status => "success", :redirect_uri => root_path, :user => { :id => user.id, :name => user.name }} }
        end
        
      else
        respond_to do |format|
          format.html { redirect_to login_path, :notice => "Email and password did not match!" }
          format.json { render :json => {:status => "invalid"}, :status => 422 }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to login_path, :notice => "Both email and password are required!" }
        format.json { render :json => {:status => "missing", :email => email.blank?, :password => password.blank?}, :status => 422 }
      end
    end
  end

  private

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :password)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/jobs/_form.html.erb
<%= form_for(@job) do |f| %>
  <% if @job.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@job.errors.count, "error") %> prohibited this job from being saved:</h2>

      <ul>
      <% @job.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :number %><br />
    <%= f.text_field :number %>
  </div>
  <div class="field">
    <%= f.label :customer %><br />
    <%= f.text_field :customer %>
  </div>
  <div class="field">
    <%= f.label :equipment %><br />
    <%= f.text_field :equipment %>
  </div>
  <div class="field">
    <%= f.fields_for :images do |builder| %>
      <%= builder.label :pic %><br />
      <%= builder.file_field :pic, :multiple => true, name: "images[pic][]" %>
    <% end %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/jobs/edit.html.erb
<h3>Editing job</h3>

<%= render 'form' %>

<%= link_to 'Show', @job %> |
<%= link_to 'Back', jobs_path %>

app/views/jobs/index.html.erb
<h3>My jobs</h3>

<table>
  <tr>
    <th>Number</th>
    <th>Customer</th>
    <th>Equipment</th>
    <th>Images</th>
    <th></th>
  </tr>

<% @jobs.each do |job| %>
  <tr>
    <td><%= job.number %></td>
    <td><%= job.customer %></td>
    <td><%= job.equipment %></td>
    <td>
      <% job.images.each do |image| %>
        <%= image_tag image.pic, {height: 45} %>
      <% end %>
    </td>
    <td><%= link_to 'Show', job %></td>
    <td><%= link_to 'Edit', edit_job_path(job) %></td>
    <td><%= link_to 'Destroy', job, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Job', new_job_path %>

app/views/jobs/new.html.erb
<h1>New job</h1>

<%= render 'form' %>

<%= link_to 'Back', jobs_path %>

app/views/jobs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Number:</b>
  <%= @job.number %>
</p>
<p>
  <b>Customer:</b>
  <%= @job.customer %>
</p>
<p>
  <b>Equiupment:</b>
  <%= @job.equipment %>
</p>
<% @job.images.each do |image| %>
  <%= image_tag image.pic if image.pic? %>
<% end %>
<%= link_to 'Edit', edit_job_path(@job) %> |
<%= link_to 'Back', jobs_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CordovaRails</title>
  <%= stylesheet_link_tag    "application", :media => "all"  %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= link_to "#{current_user.name}, logout", logout_path if user_logged_in? %>

<%= yield %>

</body>
</html>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/login.html.erb
<p id="notice"><%= notice %></p>

<%= form_for(@user, :url => create_session_path) do |f| %>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br />
    <%= f.password_field :password %>
  </div>
  <div class="actions">
    <%= f.submit "Login" %>
  </div>
<% end %>

<%= link_to 'Register', register_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>